Change TS Target to ES2015 and Enable Strict Mode
jpedroschmitz/typescript-nextjs-starter pull request #89
Opened 2021-01-21 17:52 UTC by kuasha420

Hello, 

Thanks again for this amazing template. 

One thing I consistently do after starting a new project is make this two changes for the following reason and was wondering if you'd consider adding them to the template. 

## Rationale 

1. nextjs itself only supports modern browser with es6+ support and IE11 with polyfills. We can safely use es2015 as target as compilation is done by nextjs/babel. This allows us to use advanced ecmascript features like **using spread operator to convert an Iterator to an Array without error or extra compiler flags.**

2. enabling strict mode helps us write better and safer code and it's recommended in most cases.

Let me know if any further changes needs to be done for this to be merged. 

## Changes Made

1. changed target to es2015 (es6)
2. changed strict mode to true
3. added type to src/pages/_app.tsx to pass strict mode (noImplicitAny)

## Test Plan

- [ ] pass type check `yarn type-check`
- [ ] start dev server `yarn dev`
- [ ] prod build `yarn build`

2021-01-22 19:30 UTC, jpedroschmitz requested changes
Hey @kuasha420, thanks for the PR. I think it's ok to enable strict mode for TypeScript. If anyone wants to disable it, can change it later.

About the target option, I don't see any reason not to change it since Next.js (through Babel) will compile it.

I requested just a small change on the `_app.tsx` file.

2021-01-22 19:30 UTC, jpedroschmitz commented on src/pages/_app.tsx
> +import { AppProps } from 'next/app';
I know it's a small thing, but can you put this import on the top of the file? 😅

2021-01-23 03:12 UTC, kuasha420 commented on src/pages/_app.tsx
> +import { AppProps } from 'next/app';
I've fixed it. 

Just a heads up, VSCode's organize import will put the absolute imports '@/' at the top before library imports for some reason.

I haven't found any good way of fixing that other than changing absolute import prefix from @ to ~.

2021-01-25 12:02 UTC, jpedroschmitz approved these changes
Thanks, @kuasha420 💜

2021-01-25 12:02 UTC, merged